defaults:
  - data: titanic        
  - features: titanic    
  - model: random_forest 
  - _self_               


pipeline:
  cv_folds: 5
  random_state: 42
  save_dir: models


hydra:
  run:
    dir: .